### ISSUE TITLE
[Request] Please add members of Team2

### ISSUE THREAD

**Issue by leemgs** [skkuse-adv/2019Fall_team2#1]
To, @SKKUSElab, 

Hello, My name Is Geunsik Lim. My GitHub ID is "leemgs". 
Please, give me "admin" privilege to start our team project at the "2019Fall_team2" repository.

## Members of Team2
*  장한빈, 하지크, 빙 (Binh), 임근식

**Comment by SKKUSElab** [comment]
Invitation mail has been sent.
Please check your e-mail.

**Comment by leemgs** [comment]
Checked. Thanks.
