### ISSUE TITLE
Generating UML diagrams from the  .apk file

### ISSUE THREAD

**Issue by leemgs** [skkuse-adv/2019Fall_team2#17]
We can use plugins of Android Studio to generate UML diagrams after doing the reverse engineering the  .apk file. 

![image](https://user-images.githubusercontent.com/82404/68436741-30321480-0202-11ea-9ba2-92a9a2c71d35.png)

**Comment by leemgs** [comment]
**Solution:**

Run Visual Paradigm
Do as below, pointing to Android Studio directory on step 4
enter image description here
![image](https://user-images.githubusercontent.com/82404/68436816-6d96a200-0202-11ea-9dde-30c66955a225.png)


Open Android Studio and right-click on the project.
enter image description here
![image](https://user-images.githubusercontent.com/82404/68436821-75564680-0202-11ea-940b-c87808f6fe43.png)

**Comment by hh951125** [comment]
Right now we have a UML use-case diagram.
We need to generate other UML diagrams. Let's distribute the workload.
- Class diagram
- Sequence diagram
- Deployment diagram
- Component diagram

**Comment by leemgs** [comment]
Done.
