### ISSUE TITLE
Write Requirements Specification document

### ISSUE THREAD

**Issue by beandkay** [skkuse-adv/2019Fall_team2#18]
# Issue Description
A clear and concise description of what is the requirements specification.

Expected Result
============

Detail work
===============
- Define User Requirements
   - Functional Requirements
   - Non-functional Requirements
* Define System Requirements Specification
   - Functional Requirements – Frontend
   - Functional Requirements – Backend
   - Non-Functional Requirements
* Define System Architecture
   - Frontend Diagram
   - Backend Diagram
   - Use-case Diagram

**Comment by hh951125** [comment]
I drew the diagram of the system architecture.

//Frontend diagram
![frontend diagram](https://user-images.githubusercontent.com/33246398/68565632-75bb3f80-0497-11ea-8650-b3190b6e0121.PNG)


//Backend diagram
![backend diagram](https://user-images.githubusercontent.com/33246398/68565635-781d9980-0497-11ea-881c-a5eda0911781.PNG)

//Use-case diagram
![use-case diagram](https://user-images.githubusercontent.com/33246398/68565671-92577780-0497-11ea-92d2-e8a97d282e46.PNG)

**Comment by leemgs** [comment]
Thanks. I will describe the personalization manager in milestone 3 (e.g. system design.docx).
