### ISSUE TITLE
ADD Ready: Propose new idea to improve the existing target system

### ISSUE THREAD

**Issue by leemgs** [skkuse-adv/2019Fall_team2#19]
As we all know, time is going. 
Now, we need to write a freely new idea to improve the existing target system for milestone 4. 

@beandkay , @ajid951125 , @JangHanbin  PTAL, Could you post some ideas with the comment?

**Comment by leemgs** [comment]
## My proposal for milestone4

* We need to introduce to the deep-learning system to improve the personalization facility of the existing target system.
* Also, we need to enhance database scheme by introducing alternatively as following:
   * No-SQL: MongoDB ( To handle no relational data)
   * Key-value store DB ( for getting more fast performance with the same hardware specification)
   * Time series DB (to monitor the selling status of the product in more detail)

**Comment by leemgs** [comment]
Welcome to any comments. 🛩

**Comment by beandkay** [comment]
I think we can propose the implementation of embedded Deep Learning inside the system, here specifically is the Recommend System for users.

**Comment by leemgs** [comment]
> I think we can propose the implementation of embedded Deep Learning inside the system
Looks good. 
* Discussion 1: BTW, do you mean both training and inferencing? or do you mean only inferencing for embedded DL inside the system? 
* Discussion 2: And, What is the system? Is this the mobile phone of the users? or Is this a server (= backend machine)?

**Comment by hh951125** [comment]
> > I think we can propose the implementation of embedded Deep Learning inside the system
> > Looks good.
> 
> * Discussion 1: BTW, do you mean both training and inferencing? or do you mean only inferencing for embedded DL inside the system?
> * Discussion 2: And, What is the system? Is this the mobile phone of the users? or Is this a server (= backend machine)?

- In my opinion, if we add deep learning to the current existing recommendation system, we will have both external components (learning on the server) and internal components (collecting data at user equipment). Overall the idea is not bad and can improve the system usability
- But, performance and security can drop a bit because of high computation and exposure of user data to the external system

**Comment by leemgs** [comment]
@ajid951125 , Thank you comment additional opinions. Let's embody our idea (e.g., recommendation system with deep learning)continually. :smile:
