### ISSUE TITLE
Analyzing Google's Data Analytics of the target system

### ISSUE THREAD

**Issue by leemgs** [skkuse-adv/2019Fall_team2#21]
The target system is connecting to Google Analytics to analyze the purchase pattern of the customers. 

* Google Analytics - https://marketingplatform.google.com/about/analytics/

* javascript for interconnection between the target system and google analytics - https://www.google-analytics.com/analytics.js

![image](https://user-images.githubusercontent.com/82404/68632580-61785080-0532-11ea-855c-5a927b8afc30.png)

**Comment by beandkay** [comment]
i don't think this is necessary for our work, it has nothing to do with the architecture

**Comment by leemgs** [comment]
To enhance the existing system, introducing  to the deep learning technology (e.g., CNN, RNN, Etc) and the big data-based data analytics is very helpful to us. Actually, it is a big  trend and paradigm shift without  a technical argue in the modern generation after Alphago advent. :smiley:
