### ISSUE TITLE
Create TOC for enhancing the existing system design with ADD approach

### ISSUE THREAD

**Issue by leemgs** [skkuse-adv/2019Fall_team2#24]
From now on, we have to concentrate on Milestone 4 as a final step.   
Now is an appropriate time to create conceptual design newly with the ADD approach.

Welcome to any comments to speed-up our collaboration.

**Comment by leemgs** [comment]
## Reference:
* https://resources.sei.cmu.edu/asset_files/TechnicalReport/2006_005_001_14795.pdf
  (Attribute-Driven Design [ADD], Version 2.0) 

![image](https://user-images.githubusercontent.com/82404/68774524-92f73600-0670-11ea-9d78-a91e00d5a39f.png)


@beandkay , @ajid951125 , PTAL.

**Comment by leemgs** [comment]
## 7 steps of ADD 3.0


#### Action Table
![image](https://user-images.githubusercontent.com/82404/69198692-e0940700-0b78-11ea-8137-5f2eabaded20.png)


#### Action Flow
![image](https://user-images.githubusercontent.com/82404/68774728-e5385700-0670-11ea-8202-70f2d33525d7.png)

**Comment by hh951125** [comment]
Let me do in more depth study of ADD first. BTW thanks for the details.

**Comment by beandkay** [comment]
Guys, i found this, it has the example at each step of ADD, we can use it for reference

https://resources.sei.cmu.edu/asset_files/Presentation/2015_017_101_438648.pdf

**Comment by leemgs** [comment]
To all, 
Please update this content, or propose comment opinions to make conceptual TOC for our M4 step. 
[**Notice**]  The below TOC will be continually updated by collecting the comments of team members. 

## Generating the entire TOC conceptually for doing the M4

#### The entire Table of Content (TOC)
- Introduction
- ADD Overview
- The existing architecture design (@beandkay )
- ADD Inputs (Architectural Drivers)
   - Functional Requirements
   - Design Constraints
   - Quality Attributes
   - Architectural concerns
- ADD Outputs (Outputs to expect from ADD)
   - Software element, Role, Responsibility, Property, and Relationship
- ADD (Step2 to Step 7)
   - Architectural Representation
      - Architectural View
      - Work Assignment View
   - Architecture Evaluation
      -  Example Scenario (e.g., ATAM)
      -  Example of Utility Tree
- Conclusion


---

**Comment by beandkay** [comment]
> Please update this content, or propose comment opinions to make conceptual TOC for our M4 step.

I think we should add the current architecture design section before jump into ADD Inputs and Outputs

**Comment by leemgs** [comment]
> I think we should add the current architecture design section before jump into ADD Inputs and Outputs

@beandkay Thanks, I updated the TOC above to apply your comments.

**Comment by leemgs** [comment]
As we discussed with kakaotalk, let's close this issue in advance for the goal. :smile:
