### ISSUE TITLE
Iteration 4: Constrains

### ISSUE THREAD

**Issue by beandkay** [skkuse-adv/2019Fall_team2#41]
## Step 2:
* WIP

## Step 3: 
* WIP

## Step 4:
* WIP

## Step 5: 
* WIP

## Step 6:
* WIP

## Step 7: 
* WIP

**Comment by leemgs** [comment]
Thank you for sharing us your work status. Okay. Let's utilize the Kanban board for our team project ASAP.

**Comment by leemgs** [comment]
@beandkay , Will you do Iteration4 step? At that time,  I thought that @ajid951125  handles Iteration4. 😺

**Comment by beandkay** [comment]
changes have been made to the One Drive file, please refer to it.
